import { ObjectId } from "mongodb";
import { NextRequest, NextResponse } from "next/server";
import { canEditCollection, isCmsCollection, validateCmsData } from "@/lib/cms";
import { logActivity, requireAdmin } from "@/lib/admin";
import { getDb } from "@/lib/mongodb";

function safeDocument(value: unknown): Record<string, unknown> | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const entries = Object.entries(value as Record<string, unknown>).filter(([key, item]) => !key.startsWith("$") && key !== "_id" && (typeof item !== "object" || item === null || Array.isArray(item))); return Object.fromEntries(entries); }
async function access(request: NextRequest, collection: string, method: "read" | "write") { if (!isCmsCollection(collection)) return null; const user = await requireAdmin(request); if (!user || (method === "write" && !canEditCollection(collection, user.role))) return null; return { user, collection }; }
export async function GET(request: NextRequest, { params }: { params: { collection: string } }) { const result = await access(request, params.collection, "read"); if (!result) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); try { const limit = Math.min(Number(request.nextUrl.searchParams.get("limit")) || 50, 100); const items = await (await getDb()).collection(result.collection).find().sort({ displayOrder: 1, createdAt: -1 }).limit(limit).toArray(); return NextResponse.json({ items }); } catch { return NextResponse.json({ message: "Unable to load content." }, { status: 500 }); } }
async function validateAndPrepare(collection: "projects" | "posts" | string, data: Record<string, unknown>, id?: string) { if (!isCmsCollection(collection)) return { error: "Invalid collection." }; const errors = validateCmsData(collection, data); if (errors.length) return { error: errors.join(" ") }; const db = await getDb(); if ((collection === "projects" || collection === "posts") && data.slug) { await db.collection(collection).createIndex({ slug: 1 }, { unique: true }); const duplicate = await db.collection(collection).findOne({ slug: data.slug, ...(id ? { _id: { $ne: new ObjectId(id) } } : {}) }); if (duplicate) return { error: "This slug is already in use." }; } return { db }; }
export async function POST(request: NextRequest, { params }: { params: { collection: string } }) { const result = await access(request, params.collection, "write"); if (!result) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); const data = safeDocument((await request.json()).data); if (!data) return NextResponse.json({ message: "Invalid data." }, { status: 400 }); try { const prepared = await validateAndPrepare(result.collection, data); if (prepared.error) return NextResponse.json({ message: prepared.error }, { status: 400 }); const now = new Date(); const inserted = await prepared.db!.collection(result.collection).insertOne({ ...data, createdAt: now, updatedAt: now }); await logActivity(result.user, "created", `${result.collection} entry`); return NextResponse.json({ id: inserted.insertedId }, { status: 201 }); } catch (error) { if ((error as { code?: number }).code === 11000) return NextResponse.json({ message: "This slug is already in use." }, { status: 409 }); return NextResponse.json({ message: "Unable to save content." }, { status: 500 }); } }
export async function PATCH(request: NextRequest, { params }: { params: { collection: string } }) { const result = await access(request, params.collection, "write"); if (!result) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); const body = await request.json(); const data = safeDocument(body.data); if (!data || !ObjectId.isValid(body.id)) return NextResponse.json({ message: "Invalid update." }, { status: 400 }); try { const prepared = await validateAndPrepare(result.collection, data, body.id); if (prepared.error) return NextResponse.json({ message: prepared.error }, { status: 400 }); await prepared.db!.collection(result.collection).updateOne({ _id: new ObjectId(body.id) }, { $set: { ...data, updatedAt: new Date() } }); await logActivity(result.user, "updated", `${result.collection} entry`); return NextResponse.json({ ok: true }); } catch (error) { if ((error as { code?: number }).code === 11000) return NextResponse.json({ message: "This slug is already in use." }, { status: 409 }); return NextResponse.json({ message: "Unable to update content." }, { status: 500 }); } }
export async function DELETE(request: NextRequest, { params }: { params: { collection: string } }) { const result = await access(request, params.collection, "write"); if (!result) return NextResponse.json({ message: "Unauthorized" }, { status: 401 }); const id = request.nextUrl.searchParams.get("id"); if (!id || !ObjectId.isValid(id)) return NextResponse.json({ message: "Invalid entry." }, { status: 400 }); await (await getDb()).collection(result.collection).deleteOne({ _id: new ObjectId(id) }); await logActivity(result.user, "deleted", `${result.collection} entry`); return NextResponse.json({ ok: true }); }
