import { ButtonLink } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { PageHero } from "@/components/sections/page-hero";

const values = ["Curiosity before certainty", "Clarity over clutter", "Care in the details", "Partnership over hand-off"];

export default function AboutPage() {
  return <><PageHero eyebrow="About Ayzent" title="The ideas behind more purposeful digital work." text="Ayzent Solutions is a design and technology studio for organisations with a clear sense of where they are going." /><section className="py-20 sm:py-28"><Container className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">Our story</p><div className="space-y-6 text-lg leading-relaxed text-muted"><p>We started Ayzent with a simple belief: the digital work that matters most is built with attention, not noise. It should make a business easier to understand, easier to choose, and easier to grow.</p><p>Today, we work at the point where strong ideas meet practical delivery—bringing strategy, design, and engineering into one considered process.</p></div></Container></section><section className="border-y border-line bg-surface py-20"><Container className="grid gap-12 md:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">Mission</p><h2 className="mt-4 font-display text-4xl leading-tight">Help good businesses make a stronger digital impression.</h2></div><div><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">Vision</p><h2 className="mt-4 font-display text-4xl leading-tight">A more thoughtful internet, shaped by teams that care about the people they serve.</h2></div></Container></section><section className="py-20 sm:py-28"><Container><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">What guides us</p><div className="mt-10 grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-4">{values.map((value, index) => <div key={value} className="bg-background p-7"><span className="text-xs text-gold">0{index + 1}</span><h3 className="mt-8 text-lg">{value}</h3></div>)}</div></Container></section><section className="border-t border-line py-20"><Container className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">The people</p><h2 className="mt-4 font-display text-4xl">Small team. Serious care.</h2><p className="mt-5 max-w-lg leading-relaxed text-muted">Ayzent is led by people who care about the balance of ideas, craft, and dependable execution. As we grow, that principle stays at the centre.</p></div><div className="bg-ink p-8 text-paper sm:p-10"><p className="font-display text-3xl">“The best work happens when ambition is met with honesty and care.”</p><p className="mt-8 text-sm text-paper/60">Founder, Ayzent Solutions</p></div></Container></section><section className="pb-20"><Container><div className="flex flex-col justify-between gap-6 border border-line p-8 sm:flex-row sm:items-center"><div><h2 className="font-display text-3xl">Let’s build what’s next.</h2><p className="mt-2 text-muted">Bring us the opportunity, challenge, or half-formed idea.</p></div><ButtonLink href="/contact">Start a Project</ButtonLink></div></Container></section></>;
}
