import Link from "next/link";
import { ButtonLink } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { ProjectCard } from "@/components/sections/project-card";
import { getClientLogos, getFaqs, getProjects, getServices, getTestimonials } from "@/lib/content";

export const dynamic = "force-dynamic";
export default async function Home() {
  const [faqs, projects, services, testimonials, clientLogos] = await Promise.all([getFaqs(), getProjects(), getServices(), getTestimonials(), getClientLogos()]);
  const featuredProjects = projects.filter((project) => project.featured).length ? projects.filter((project) => project.featured) : projects;
  return (
    <>
      <section className="relative overflow-hidden border-b border-line"><Container className="grid min-h-[calc(100vh-5rem)] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="animate-fade-up text-xs font-medium uppercase tracking-[0.18em] text-gold">Ayzent Solutions</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[.98] sm:text-7xl">Digital work with <em className="font-normal text-gold">real momentum.</em></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-muted">We build thoughtful websites, brands, and digital products for businesses ready to make their next move count.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/contact">Start a Project</ButtonLink><ButtonLink href="/projects" variant="secondary">Explore Our Work</ButtonLink></div></div><div className="relative hidden aspect-square bg-ink p-8 lg:block"><div className="absolute inset-8 border border-gold/60" /><div className="absolute inset-0 grid place-items-center"><span className="font-display text-6xl text-paper">A.</span></div><p className="absolute bottom-8 left-8 max-w-[14rem] text-sm leading-relaxed text-paper/70">Strategy, design and technology working in the same direction.</p></div></Container></section>
      <section className="border-b border-line py-20 sm:py-28"><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">What we do</p><div><h2 className="font-display text-4xl leading-tight sm:text-5xl">A partner for the ideas that matter next.</h2><p className="mt-6 max-w-2xl leading-relaxed text-muted">Ayzent brings strategy, design, and engineering together to create digital experiences that are useful, distinct, and built to last.</p><Link href="/about" className="mt-6 inline-block text-sm hover:text-gold">More about Ayzent →</Link></div></Container></section>
      <section className="py-20 sm:py-28"><Container><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">Capabilities</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Made to move you forward.</h2></div><Link href="/services" className="hidden text-sm sm:block hover:text-gold">All services →</Link></div><div className="mt-12 grid border-t border-line sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <div key={service.title} className="border-b border-line py-7 sm:pr-8 lg:pr-10"><span className="text-xs text-gold">{service.number}</span><h3 className="mt-5 text-lg">{service.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{service.text}</p></div>)}</div></Container></section>
      <section className="border-y border-line bg-surface py-20 sm:py-28"><Container><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">Selected work</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="font-display text-4xl sm:text-5xl">Work that carries weight.</h2><Link href="/projects" className="text-sm hover:text-gold">All projects →</Link></div><div className="mt-12 grid gap-10 md:grid-cols-2">{featuredProjects.slice(0, 2).map((project) => <ProjectCard key={project.slug} project={project} />)}</div></Container></section>
      <section className="py-20 sm:py-28"><Container className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">Why Ayzent</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Good work begins with a good working relationship.</h2></div><div className="grid gap-8 sm:grid-cols-2"><div><h3>Thoughtful by default</h3><p className="mt-3 text-sm leading-relaxed text-muted">We ask better questions before we start making things.</p></div><div><h3>Built together</h3><p className="mt-3 text-sm leading-relaxed text-muted">You get an involved, clear-eyed partner—not a black box.</p></div><div><h3>Made for real life</h3><p className="mt-3 text-sm leading-relaxed text-muted">We design for the people using, running, and growing your business.</p></div><div><h3>Quality that holds up</h3><p className="mt-3 text-sm leading-relaxed text-muted">The small details get the same attention as the big idea.</p></div></div></Container></section>
      <section className="border-y border-line py-16"><Container><p className="text-center text-xs font-medium uppercase tracking-[0.18em] text-muted">Trusted by ambitious teams</p><div className="mt-10 grid grid-cols-2 gap-6 text-center font-display text-2xl text-muted sm:grid-cols-4">{(clientLogos.length ? clientLogos : [{ name: "Northstar" }, { name: "Atlas" }, { name: "FORM & FIELD" }, { name: "Morrow" }]).map((client) => <span key={client.name}>{client.name}</span>)}</div></Container></section>
      {testimonials.length > 0 && <section className="py-20 sm:py-28"><Container><p className="text-xs font-medium uppercase tracking-[.18em] text-gold">Client perspectives</p><div className="mt-8 grid gap-5 md:grid-cols-2">{testimonials.slice(0, 2).map((testimonial) => <figure className="border border-line p-7" key={testimonial.clientName}><blockquote className="font-display text-2xl leading-relaxed">“{testimonial.text}”</blockquote><figcaption className="mt-6 text-sm text-muted">{testimonial.clientName}{testimonial.roleCompany ? ` · ${testimonial.roleCompany}` : ""}</figcaption></figure>)}</div></Container></section>}
      <section className="py-20 sm:py-28"><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">Common questions</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Let’s make it clear.</h2></div><div>{faqs.map(([question, answer]) => <details key={question} className="border-t border-line py-5 last:border-b"><summary className="cursor-pointer list-none pr-8 text-lg marker:hidden">{question}<span className="float-right text-gold">+</span></summary><p className="mt-4 max-w-xl text-sm leading-relaxed text-muted">{answer}</p></details>)}</div></Container></section>
      <section className="bg-ink py-20 text-paper sm:py-28"><Container className="text-center"><p className="text-xs font-medium uppercase tracking-[0.18em] text-gold">A good place to begin</p><h2 className="mx-auto mt-5 max-w-3xl font-display text-4xl leading-tight sm:text-6xl">Have something worthwhile in mind?</h2><p className="mx-auto mt-5 max-w-xl text-paper/65">Tell us what you are trying to achieve. We will help you find the next right step.</p><ButtonLink href="/contact" className="mt-8 bg-gold text-ink hover:bg-paper">Discuss Your Requirements</ButtonLink></Container></section>
    </>
  );
}
