export type FieldType = "text" | "textarea" | "markdown" | "number" | "url" | "email" | "checkbox" | "select" | "tags" | "image";
export type AdminField = { name: string; label: string; type: FieldType; required?: boolean; options?: string[]; hint?: string };
const status = ["draft", "published", "archived"];
export const collectionFields: Record<string, AdminField[]> = {
  services: [{ name: "title", label: "Service name", type: "text", required: true }, { name: "text", label: "Summary", type: "textarea", required: true }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "published", label: "Published", type: "checkbox" }],
  projects: [{ name: "name", label: "Project name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true, hint: "Lowercase words separated by hyphens." }, { name: "overview", label: "Overview", type: "textarea", required: true }, { name: "category", label: "Category", type: "text", required: true }, { name: "client", label: "Client", type: "text" }, { name: "coverImage", label: "Cover image URL", type: "image" }, { name: "challenge", label: "Challenge", type: "textarea" }, { name: "solution", label: "Solution", type: "textarea" }, { name: "features", label: "Features", type: "tags" }, { name: "technologies", label: "Technologies", type: "tags" }, { name: "gallery", label: "Gallery image URLs", type: "tags" }, { name: "liveLink", label: "Live link", type: "url" }, { name: "status", label: "Status", type: "select", options: status }, { name: "outcomes", label: "Outcomes", type: "textarea" }, { name: "featured", label: "Featured", type: "checkbox" }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "published", label: "Published", type: "checkbox" }],
  posts: [{ name: "title", label: "Title", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }, { name: "excerpt", label: "Excerpt", type: "textarea", required: true }, { name: "content", label: "Article content", type: "markdown", required: true }, { name: "category", label: "Category", type: "text", required: true }, { name: "tags", label: "Tags", type: "tags" }, { name: "coverImage", label: "Open Graph / cover image URL", type: "image" }, { name: "seoTitle", label: "SEO title", type: "text" }, { name: "seoDescription", label: "SEO description", type: "textarea" }, { name: "status", label: "Status", type: "select", options: status }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "published", label: "Published", type: "checkbox" }],
  categories: [{ name: "name", label: "Name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }, { name: "displayOrder", label: "Display order", type: "number" }],
  tags: [{ name: "name", label: "Name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }],
  comments: [{ name: "status", label: "Moderation status", type: "select", options: ["pending", "approved", "rejected"], required: true }],
  team: [{ name: "name", label: "Name", type: "text", required: true }, { name: "role", label: "Role", type: "text", required: true }, { name: "shortBio", label: "Short bio", type: "textarea" }, { name: "image", label: "Image URL", type: "image" }, { name: "socialLinks", label: "Social links", type: "tags", hint: "One URL per item." }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "published", label: "Published", type: "checkbox" }],
  testimonials: [{ name: "clientName", label: "Client name", type: "text", required: true }, { name: "roleCompany", label: "Role / company", type: "text" }, { name: "text", label: "Testimonial", type: "textarea", required: true }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "active", label: "Active", type: "checkbox" }],
  faqs: [{ name: "question", label: "Question", type: "text", required: true }, { name: "answer", label: "Answer", type: "textarea", required: true }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "active", label: "Active", type: "checkbox" }],
  clientLogos: [{ name: "name", label: "Client name", type: "text", required: true }, { name: "logo", label: "Logo URL", type: "image" }, { name: "link", label: "Website URL", type: "url" }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "active", label: "Active", type: "checkbox" }],
  jobs: [{ name: "title", label: "Job title", type: "text", required: true }, { name: "description", label: "Description", type: "markdown", required: true }, { name: "requirements", label: "Requirements", type: "tags" }, { name: "location", label: "Location", type: "text" }, { name: "type", label: "Employment type", type: "text" }, { name: "applicationInstructions", label: "Application instructions", type: "textarea" }, { name: "status", label: "Status", type: "select", options: ["open", "closed"] }, { name: "displayOrder", label: "Display order", type: "number" }],
  inquiries: [{ name: "status", label: "Inquiry status", type: "select", options: ["New", "Contacted", "In Progress", "Converted", "Closed"], required: true }],
  newsletterSubscribers: [{ name: "status", label: "Subscriber status", type: "select", options: ["active", "unsubscribed"], required: true }],
  socialLinks: [{ name: "label", label: "Label", type: "text", required: true }, { name: "url", label: "Profile URL", type: "url", required: true }, { name: "displayOrder", label: "Display order", type: "number" }, { name: "active", label: "Active", type: "checkbox" }],
  announcements: [{ name: "title", label: "Title", type: "text", required: true }, { name: "content", label: "Content", type: "textarea", required: true }, { name: "image", label: "Optional image URL", type: "image" }, { name: "ctaText", label: "CTA text", type: "text" }, { name: "ctaLink", label: "CTA link", type: "url" }, { name: "active", label: "Active", type: "checkbox" }],
};
