import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/container";
import { ButtonLink } from "@/components/ui/button";
import { Markdown } from "@/components/content/markdown";
import { getProduct, getProducts } from "@/lib/content";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = await getProduct((await params).slug); if (!product) return {}; return { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, alternates: { canonical: `/products/${product.slug}` }, openGraph: { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, images: product.coverImage ? [product.coverImage] : [] }, twitter: { card: "summary_large_image" } }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const product = await getProduct((await params).slug); if (!product) notFound(); const gallery = product.gallery?.filter(Boolean) || []; return <><section className="py-16 sm:py-24"><Container><p className="text-xs uppercase tracking-[.18em] text-gold">{product.category || "Product"}</p><h1 className="mt-4 max-w-4xl font-display text-5xl sm:text-7xl">{product.name}</h1><p className="mt-6 max-w-2xl text-lg text-muted">{product.shortDescription}</p>{product.coverImage && <div className="relative mt-10 aspect-[16/8]"><Image src={product.coverImage} alt={`${product.name} cover image`} fill className="object-cover" priority sizes="100vw" /></div>}</Container></section><section className="border-t border-line py-16"><Container className="grid gap-12 lg:grid-cols-[1.5fr_.5fr]"><article className="prose prose-neutral max-w-none dark:prose-invert"><Markdown content={product.content} />{gallery.length > 0 && <div className="not-prose mt-10 grid gap-4 sm:grid-cols-2">{gallery.map((src, index) => <div className="relative aspect-[4/3]" key={src}><Image src={src} alt={`${product.name} gallery image ${index + 1}`} fill className="object-cover" sizes="(min-width: 640px) 50vw, 100vw" /></div>)}</div>}</article><aside>{product.technologies?.length ? <><h2 className="font-display text-2xl">Built with</h2><p className="mt-3 text-muted">{product.technologies.join(" · ")}</p></> : null}{product.features?.length ? <ul className="mt-8 space-y-2 text-muted">{product.features.map((feature) => <li key={feature}>{feature}</li>)}</ul> : null}{(product.ctaLink || product.url) && <div className="mt-8"><ButtonLink href={product.ctaLink || product.url!}>{product.ctaText || "Visit product"}</ButtonLink></div>}</aside></Container></section></>; }
